//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public int CustomerCustID { get; set; }
        public string ProductName { get; set; }
        public string PurchaseDate { get; set; }
        public string Quantity { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
